<a href="https://colab.research.google.com/github/lkarjun/workouts-pytorch/blob/main/basics/2_fundamentals_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Fundamentals
### Tutorial 2

https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html

https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises


In [1]:
# Tensors

In [2]:
import torch
import numpy as np

### Basics

In [3]:
# Initializing a Tensor

data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

x_data.shape

torch.Size([2, 2])

In [4]:
# From numpy array

np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [10]:
# Scalar
## Its a single number and zero dim tensor
scalar = torch.tensor(4)
scalar, scalar.ndim

(tensor(4), 0)

In [13]:
# Vector
## Single dim tensor, contain mulitple value

vector = torch.tensor([7, 7])
vector, vector.ndim, vector.shape

(tensor([7, 7]), 1, torch.Size([2]))

In [18]:
# Matrix
## Contain extra dim and more values

MATRIX = torch.tensor([[7, 8], [9, 10]])

MATRIX, MATRIX.ndim, MATRIX.shape

(tensor([[ 7,  8],
         [ 9, 10]]),
 2,
 torch.Size([2, 2]))

In [19]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [20]:
# The dim to outer to inner
## That means 1 dim of 3 by 3
TENSOR.ndim, TENSOR.shape

(3, torch.Size([1, 3, 3]))

In [ ]:
# Random Tensors

