<a href="https://colab.research.google.com/github/lkarjun/workouts-pytorch/blob/main/basics/2_fundamentals_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Fundamentals
### Tutorial 2

https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html

https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises


In [ ]:
# Tensors

In [1]:
import torch
import numpy as np

### Basics

In [2]:
# Initializing a Tensor

data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

x_data.shape

torch.Size([2, 2])

In [3]:
# From numpy array

np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [4]:
# Scalar
## Its a single number and zero dim tensor
scalar = torch.tensor(4)
scalar, scalar.ndim

(tensor(4), 0)

In [5]:
# Vector
## Single dim tensor, contain mulitple value

vector = torch.tensor([7, 7])
vector, vector.ndim, vector.shape

(tensor([7, 7]), 1, torch.Size([2]))

In [6]:
# Matrix
## Contain extra dim and more values

MATRIX = torch.tensor([[7, 8], [9, 10]])

MATRIX, MATRIX.ndim, MATRIX.shape

(tensor([[ 7,  8],
         [ 9, 10]]),
 2,
 torch.Size([2, 2]))

In [7]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [8]:
# The dim to outer to inner
## That means 1 dim of 3 by 3
TENSOR.ndim, TENSOR.shape

(3, torch.Size([1, 3, 3]))

In [11]:
# Random Tensors

random_tensor = torch.randn(size=(3, 4))
random_tensor,random_tensor.dtype

(tensor([[ 0.9028,  0.7284, -0.7103,  0.1600],
         [-0.0314,  1.3830,  1.1037, -0.2028],
         [-0.4803,  0.7899, -1.2212,  0.0392]]),
 torch.float32)

In [12]:
random_image = torch.randn(size=(224, 224, 3))

In [13]:
# Zeros and ones

zeros = torch.zeros(size=(2, 3))
ones = torch.ones(size=(3, 1))

In [16]:
# Creating a Range of Tensor

zero_to_ten = torch.arange(0, 10, 2)
zero_to_ten

tensor([0, 2, 4, 6, 8])

In [18]:
torch.zeros_like(zero_to_ten)

tensor([0, 0, 0, 0, 0])

In [21]:
# Tensor datatype

## precision in computing 
### Is the amount of detail used to describe a number
### The higher the precision, the more the details

### all tensor should be in same size, type, and in device

float_32_tensor = torch.randn(size=(2, 2), dtype=None)

float_32_tensor, float_32_tensor.dtype

(tensor([[ 0.2750, -0.3766],
         [-2.1178,  0.9551]]),
 torch.float32)